image: appwisebe/laravel-docker:8.1

pipelines:
  branches:
    development:
      - step:
          name: Deploy to Development
          deployment: development
          caches:
            - node
            - npm
          script:
            - npm install -g pnpm
            - pnpm install --frozen-lockfile
            - pnpm $BITBUCKET_BRANCH
            - rsync -crltDzv ./dist/ $DEPLOY_URL:www/htdocs/public --exclude=.env --exclude=.git --exclude=.cert --exclude=.vscode
    test:
      - step:
          name: Deploy to Test
          deployment: test
          caches:
            - node
            - npm
          script:
            - npm install -g pnpm
            - pnpm install --frozen-lockfile
            - pnpm $BITBUCKET_BRANCH
            - rsync -crltDzv ./dist/ $DEPLOY_URL:www/htdocs/public --exclude=.env --exclude=.git --exclude=.cert --exclude=.vscode
    staging:
      - step:
          name: Deploy to Staging
          deployment: staging
          caches:
            - node
            - npm
          script:
            - npm install -g pnpm
            - pnpm install --frozen-lockfile
            - pnpm $BITBUCKET_BRANCH
            - rsync -crltDzv ./dist/ $DEPLOY_URL:www/htdocs/public --exclude=.env --exclude=.git --exclude=.cert --exclude=.vscode
    production:
      - step:
          name: Deploy to Production
          deployment: production
          caches:
            - node
            - npm
          script:
            - npm install -g pnpm
            - pnpm install --frozen-lockfile
            - pnpm $BITBUCKET_BRANCH
            - rsync -crltDzv ./dist/ $DEPLOY_URL:www/htdocs/public --exclude=.env --exclude=.git --exclude=.cert --exclude=.vscode
definitions:
  caches:
    npm: $HOME/.npm
