import containerQueries from '@tailwindcss/container-queries'
import type { Config } from 'tailwindcss'

export default {
  content: [
    './index.html',
    './src/**/*.{vue,ts}',
    './node_modules/@wisemen/vue-core/**/*.js',
  ],
  darkMode: 'class',
  plugins: [
    containerQueries,
  ],
  theme: {
    extend: {
      animation: {
        'indeterminate-loader': 'indeterminate-loader 2s infinite',
      },
      backgroundColor: {
        'active': 'var(--bg-active)',
        'auth': 'rgb(11, 32, 63)',
        'auth-blur': 'rgba(106,170,225,1)',
        'brand-primary': 'var(--bg-brand-primary)',
        'brand-primary-alt': 'var(--bg-brand-primary-alt)',
        'brand-secondary': 'var(--bg-brand-secondary)',
        'brand-section': 'var(--bg-brand-section)',
        'brand-section-subtle': 'var(--bg-brand-section-subtle)',
        'brand-solid': 'var(--bg-brand-solid)',
        'brand-solid-hover': 'var(--bg-brand-solid-hover)',
        'disabled': 'var(--bg-disabled)',
        'disabled-subtle': 'var(--bg-disabled-subtle)',
        'error-primary': 'var(--bg-error-primary)',
        'error-secondary': 'var(--bg-error-secondary)',
        'error-solid': 'var(--bg-error-solid)',
        'overlay': 'var(--bg-overlay)',
        'primary': 'var(--bg-primary)',
        'primary-alt': 'var(--bg-primary-alt)',
        'primary-hover': 'var(--bg-primary-hover)',
        'primary-solid': 'var(--bg-primary-solid)',
        'quaternary': 'var(--bg-quaternary)',
        'secondary': 'var(--bg-secondary)',
        'secondary-alt': 'var(--bg-secondary-alt)',
        'secondary-hover': 'var(--bg-secondary-hover)',
        'secondary-solid': 'var(--bg-secondary-solid)',
        'secondary-subtle': 'var(--bg-secondary-subtle)',
        'success-primary': 'var(--bg-success-primary)',
        'success-secondary': 'var(--bg-success-secondary)',
        'success-solid': 'var(--bg-success-solid)',
        'tertiary': 'var(--bg-tertiary)',
        'warning-primary': 'var(--bg-warning-primary)',
        'warning-secondary': 'var(--bg-warning-secondary)',
        'warning-solid': 'var(--bg-warning-solid)',
      },
      borderColor: {
        'brand': 'var(--border-brand)',
        'brand-alt': 'var(--border-brand-alt)',
        'disabled': 'var(--border-disabled)',
        'disabled-subtle': 'var(--border-disabled-subtle)',
        'error': 'var(--border-error)',
        'error-subtle': 'var(--border-error-subtle)',
        'primary': 'var(--border-primary)',
        'secondary': 'var(--border-secondary)',
        'tertiary': 'var(--border-tertiary)',
      },
      boxShadow: {
        'button-primary': '0px 4px 16px 0px rgba(0, 96, 169, 0.30)',
        'lg': 'var(--shadow-lg)',
        'sidebar-item-active': '0px 4px 16px 0px #0060A94D',
        'sm': 'var(--shadow-sm)',
      },
      colors: {
        'brand-primary-25': 'var(--brand-primary-25)',
        'brand-primary-50': 'var(--brand-primary-50)',
        'brand-primary-100': 'var(--brand-primary-100)',
        'brand-primary-200': 'var(--brand-primary-200)',
        'brand-primary-300': 'var(--brand-primary-300)',
        'brand-primary-400': 'var(--brand-primary-400)',
        'brand-primary-500': 'var(--brand-primary-500)',
        'brand-primary-600': 'var(--brand-primary-600)',
        'brand-primary-700': 'var(--brand-primary-700)',
        'brand-primary-800': 'var(--brand-primary-800)',
        'brand-primary-900': 'var(--brand-primary-900)',
        'brand-primary-950': 'var(--brand-primary-950)',
        'brand-primary-gradient-from': '#103266',
        'brand-primary-gradient-to': '#0A1F3E',
        'error-25': 'var(--error-25)',
        'error-50': 'var(--error-50)',
        'error-100': 'var(--error-100)',
        'error-200': 'var(--error-200)',
        'error-300': 'var(--error-300)',
        'error-400': 'var(--error-400)',
        'error-500': 'var(--error-500)',
        'error-600': 'var(--error-600)',
        'error-700': 'var(--error-700)',
        'error-800': 'var(--error-800)',
        'error-900': 'var(--error-900)',
        'error-950': 'var(--error-950)',

        'fg-brand-primary': 'var(--fg-brand-primary)',
        'fg-brand-primary-alt': 'var(--fg-brand-primary-alt)',

        'fg-brand-secondary': 'var(--fg-brand-secondary)',
        'fg-disabled': 'var(--fg-disabled)',
        'fg-disabled-subtle': 'var(--fg-disabled-subtle)',
        'fg-error-primary': 'var(--fg-error-primary)',
        'fg-error-secondary': 'var(--fg-error-secondary)',
        'fg-primary': 'var(--fg-primary)',
        'fg-quarternary': 'var(--fg-quarternary)',
        'fg-quarternary-hover': 'var(--fg-quarternary-hover)',
        'fg-quinary': 'var(--fg-quinary)',
        'fg-quinary-hover': 'var(--fg-quinary-hover)',

        'fg-secondary': 'var(--fg-secondary)',
        'fg-secondary-hover': 'var(--fg-secondary-hover)',
        'fg-senary': 'var(--fg-senary)',
        'fg-success-primary': 'var(--fg-success-primary)',
        'fg-success-secondary': 'var(--fg-success-secondary)',
        'fg-tertiary': 'var(--fg-tertiary)',
        'fg-tertiary-hover': 'var(--fg-tertiary-hover)',
        'fg-warning-primary': 'var(--fg-warning-primary)',
        'fg-warning-secondary': 'var(--fg-warning-secondary)',
        'fg-white': 'var(--fg-white)',
        'gray-25': 'var(--gray-25)',
        'gray-50': 'var(--gray-50)',

        'gray-100': 'var(--gray-100)',
        'gray-200': 'var(--gray-200)',
        'gray-300': 'var(--gray-300)',
        'gray-400': 'var(--gray-400)',
        'gray-500': 'var(--gray-500)',
        'gray-600': 'var(--gray-600)',
        'gray-700': 'var(--gray-700)',
        'gray-800': 'var(--gray-800)',
        'gray-900': 'var(--gray-900)',
        'gray-950': 'var(--gray-950)',
        'icon-fg-brand-on-brand': 'var(--icon-fg-brand-on-brand)',
        'icon-fg-on-brand': 'var(--icon-fg-on-brand)',

        'purple-25': 'var(--purple-25)',
        'purple-50': 'var(--purple-50)',
        'purple-100': 'var(--purple-100)',
        'purple-200': 'var(--purple-200)',
        'purple-300': 'var(--purple-300)',
        'purple-400': 'var(--purple-400)',
        'purple-500': 'var(--purple-500)',
        'purple-600': 'var(--purple-600)',
        'purple-700': 'var(--purple-700)',
        'purple-800': 'var(--purple-800)',
        'purple-900': 'var(--purple-900)',
        'purple-950': 'var(--purple-950)',

        'success-25': 'var(--success-25)',
        'success-50': 'var(--success-50)',
        'success-100': 'var(--success-100)',
        'success-200': 'var(--success-200)',
        'success-300': 'var(--success-300)',
        'success-400': 'var(--success-400)',
        'success-500': 'var(--success-500)',
        'success-600': 'var(--success-600)',
        'success-700': 'var(--success-700)',
        'success-800': 'var(--success-800)',
        'success-900': 'var(--success-900)',
        'success-950': 'var(--success-950)',

        'utility-blue-dark-25': 'var(--utility-blue-dark-25)',
        'utility-blue-dark-50': 'var(--utility-blue-dark-50)',
        'utility-blue-dark-100': 'var(--utility-blue-dark-100)',
        'utility-blue-dark-200': 'var(--utility-blue-dark-200)',
        'utility-blue-dark-300': 'var(--utility-blue-dark-300)',
        'utility-blue-dark-400': 'var(--utility-blue-dark-400)',
        'utility-blue-dark-500': 'var(--utility-blue-dark-500)',
        'utility-blue-dark-600': 'var(--utility-blue-dark-600)',
        'utility-blue-dark-700': 'var(--utility-blue-dark-700)',
        'utility-blue-dark-800': 'var(--utility-blue-dark-800)',
        'utility-blue-dark-900': 'var(--utility-blue-dark-900)',
        'utility-blue-dark-950': 'var(--utility-blue-dark-950)',

        'warning-25': 'var(--warning-25)',
        'warning-50': 'var(--warning-50)',
        'warning-100': 'var(--warning-100)',
        'warning-200': 'var(--warning-200)',
        'warning-300': 'var(--warning-300)',
        'warning-400': 'var(--warning-400)',
        'warning-500': 'var(--warning-500)',
        'warning-600': 'var(--warning-600)',
        'warning-700': 'var(--warning-700)',
        'warning-800': 'var(--warning-800)',
        'warning-900': 'var(--warning-900)',
        'warning-950': 'var(--warning-950)',
      },
      gradientColorStops: {
        'auth-bg': 'rgb(11, 32, 63)',
        'auth-bg-from': 'rgb(11, 32, 63, 0.4)',
        'auth-bg-via': 'rgb(11, 32, 63, 0.9)',
        'bg-primary': 'var(--bg-primary)',
      },
      keyframes: {
        'indeterminate-loader': {
          '0%': {
            left: '-100%',
          },
          '100%': {
            left: '100%',
          },
        },
      },
      ringOffsetColor: {
        DEFAULT: 'var(--bg-primary)',
      },
      textColor: {
        'brand-primary': 'var(--text-brand-primary)',
        'brand-secondary': 'var(--text-brand-secondary)',
        'brand-tertiary': 'var(--text-brand-tertiary)',
        'brand-tertiary-alt': 'var(--text-brand-tertiary-alt)',
        'disabled': 'var(--text-disabled)',
        'error-primary': 'var(--text-error-primary)',
        'placeholder': 'var(--text-placeholder)',
        'placeholder-subtle': 'var(--text-placeholder-subtle)',
        'primary': 'var(--text-primary)',
        'primary-on-brand': 'var(--text-primary-on-brand)',
        'quaternary': 'var(--text-quaternary)',
        'quaternary-on-brand': 'var(--text-quaternary-on-brand)',
        'secondary': 'var(--text-secondary)',
        'secondary-hover': 'var(--text-secondary-hover)',
        'secondary-on-brand': 'var(--text-secondary-on-brand)',
        'success-primary': 'var(--text-success-primary)',
        'tertiary': 'var(--text-tertiary)',
        'tertiary-hover': 'var(--text-tertiary-hover)',
        'tertiary-on-brand': 'var(--text-tertiary-on-brand)',
        'warning-primary': 'var(--text-warning-primary)',
        'white': 'var(--text-white)',
      },
      transitionTimingFunction: {
        'sidebar-collapse': 'cubic-bezier(0.25, 0.8, 0.25, 1)',
      },
      width: {
        'dialog-sm': '26rem',
        'drawer-lg': '40rem',
        'drawer-md': '30rem',
      },
    },
    fontFamily: {
      sans: 'Inter Variable',
    },
    fontSize: {
      '4xl': [
        'var(--text-4xl)',
        'var(--line-height-4xl)',
      ],
      'display-sm': [
        'var(--text-display-sm)',
        'var(--line-height-display-sm)',
      ],
      'display-xs': [
        'var(--text-display-xs)',
        'var(--line-height-display-xs)',
      ],
      'lg': [
        'var(--text-lg)',
        'var(--line-height-lg)',
      ],
      'md': [
        'var(--text-md)',
        'var(--line-height-md)',
      ],
      'sm': [
        'var(--text-sm)',
        'var(--line-height-sm)',
      ],
      'xl': [
        'var(--text-xl)',
        'var(--line-height-xl)',
      ],
      'xs': [
        'var(--text-xs)',
        'var(--line-height-xs)',
      ],
    },
    gap: {
      '2xl': 'var(--spacing-2xl)',
      '3xl': 'var(--spacing-3xl)',
      '4xl': 'var(--spacing-4xl)',
      '5xl': 'var(--spacing-5xl)',
      '6xl': 'var(--spacing-6xl)',
      '7xl': 'var(--spacing-7xl)',
      '8xl': 'var(--spacing-8xl)',
      '9xl': 'var(--spacing-9xl)',
      '10xl': 'var(--spacing-10xl)',
      '11xl': 'var(--spacing-11xl)',
      'lg': 'var(--spacing-lg)',
      'md': 'var(--spacing-md)',
      'none': 'var(--spacing-none)',
      'sm': 'var(--spacing-sm)',
      'xl': 'var(--spacing-xl)',
      'xs': 'var(--spacing-xs)',
      'xxs': 'var(--spacing-xxs)',
    },
    lineHeight: {
      'display-sm': 'var(--line-height-display-sm)',
      'display-xs': 'var(--line-height-display-xs)',
      'lg': 'var(--line-height-lg)',
      'md': 'var(--line-height-md)',
      'sm': 'var(--line-height-sm)',
      'xl': 'var(--line-height-xl)',
      'xs': 'var(--line-height-xs)',
    },
    margin: {
      '0': '0',
      '2xl': 'var(--spacing-2xl)',
      '3xl': 'var(--spacing-3xl)',
      '4xl': 'var(--spacing-4xl)',
      '5xl': 'var(--spacing-5xl)',
      '6xl': 'var(--spacing-6xl)',
      '7xl': 'var(--spacing-7xl)',
      '8xl': 'var(--spacing-8xl)',
      '9xl': 'var(--spacing-9xl)',
      '10xl': 'var(--spacing-10xl)',
      '11xl': 'var(--spacing-11xl)',
      'auto': 'auto',
      'lg': 'var(--spacing-lg)',
      'md': 'var(--spacing-md)',
      'none': 'var(--spacing-none)',
      'sm': 'var(--spacing-sm)',
      'xl': 'var(--spacing-xl)',
      'xs': 'var(--spacing-xs)',
      'xxs': 'var(--spacing-xxs)',
    },

    padding: {
      '0': '0',
      '2xl': 'var(--spacing-2xl)',
      '3xl': 'var(--spacing-3xl)',
      '4xl': 'var(--spacing-4xl)',
      '5xl': 'var(--spacing-5xl)',
      '6xl': 'var(--spacing-6xl)',
      '7xl': 'var(--spacing-7xl)',
      '8xl': 'var(--spacing-8xl)',
      '9xl': 'var(--spacing-9xl)',
      '10xl': 'var(--spacing-10xl)',
      '11xl': 'var(--spacing-11xl)',
      'lg': 'var(--spacing-lg)',
      'md': 'var(--spacing-md)',
      'none': 'var(--spacing-none)',
      'sm': 'var(--spacing-sm)',
      'xl': 'var(--spacing-xl)',
      'xs': 'var(--spacing-xs)',
      'xxs': 'var(--spacing-xxs)',
    },
  },
} satisfies Config
