import { defineStyleConfig } from '@wisemen/vue-core'

defineStyleConfig({
  colorScheme: '*',
  config: {
    '--text-field-bg-color-default': 'transparent',
    '--text-field-bg-color-disabled': 'transparent',
    '--text-field-bg-color-error': 'transparent',
    '--text-field-bg-color-focus': 'transparent',
    '--text-field-bg-color-hover': 'transparent',
    '--text-field-border-bottom-color-default': 'transparent',
    '--text-field-border-bottom-color-disabled': 'transparent',
    '--text-field-border-bottom-color-error': 'transparent',
    '--text-field-border-bottom-color-focus': 'transparent',
    '--text-field-border-bottom-color-hover': 'transparent',
    '--text-field-border-left-color-default': 'transparent',
    '--text-field-border-left-color-disabled': 'transparent',
    '--text-field-border-left-color-error': 'transparent',
    '--text-field-border-left-color-focus': 'transparent',
    '--text-field-border-left-color-hover': 'transparent',
    '--text-field-border-right-color-default': 'transparent',
    '--text-field-border-right-color-disabled': 'transparent',
    '--text-field-border-right-color-error': 'transparent',
    '--text-field-border-right-color-focus': 'transparent',
    '--text-field-border-right-color-hover': 'transparent',
    '--text-field-border-top-color-default': 'transparent',
    '--text-field-border-top-color-disabled': 'transparent',
    '--text-field-border-top-color-error': 'transparent',
    '--text-field-border-top-color-focus': 'transparent',
    '--text-field-border-top-color-hover': 'transparent',
    '--text-field-icon-color-default': 'var(--gray-300)',
    '--text-field-icon-color-disabled': 'var(-gray-300)',
    '--text-field-icon-color-error': 'var(--gray-300)',
    '--text-field-icon-color-focus': 'var(--gray-300)',
    '--text-field-icon-color-hover': 'var(--gray-300)',
    '--text-field-shadow-default': 'none',
    '--text-field-shadow-disabled': 'none',
    '--text-field-shadow-error': 'none',
    '--text-field-shadow-focus': 'none',
    '--text-field-shadow-hover': 'none',
    '--text-field-text-color-default': 'var(--color-white)',
    '--text-field-text-color-disabled': 'var(--color-white)',
    '--text-field-text-color-error': 'var(--color-white)',
    '--text-field-text-color-focus': 'var(--color-white)',
    '--text-field-text-color-hover': 'var(--color-white)',
  },
  theme: '*',
  variant: 'transparent',
  component: 'textField',
})
