---
name: PR Check

on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

jobs:
  lint-build-test:
    uses: wisemen-digital/devops-github-actions/.github/workflows/web-build-and-test.yml@main
    if: github.event.pull_request.draft == false
    with:
      test-playwright-image: 'mcr.microsoft.com/playwright:v1.51.0'
